/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFAZ;

import com.mongodb.BasicDBObject;
import com.mongodb.DBCursor;
import com.mongodb.DBObject;
import javax.swing.table.DefaultTableModel;
import static tareainvestigacion.mongodb.TareaInvestigacionMONGODB.coleccion;
import static tareainvestigacion.mongodb.TareaInvestigacionMONGODB.db;

/**
 *
 * @author M Express
 */
public class VerComentarios extends javax.swing.JFrame {

    int numPartido;
    String codUsuario;
    /**
     * Creates new form CRUDcomentarios
     */
    public VerComentarios() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarInterfaz();
        cargarDatos();
    }
    public VerComentarios(int numPart, String codUser) {
        this.numPartido = numPart;
        this.codUsuario = codUser;
        initComponents();
        this.setLocationRelativeTo(null);
        setUsuario();
        setNumPartido();
    }
    
    public void setNumPartido(){
        lblInfo.setText(numPartido+"");
    }
    
    public void setUsuario(){
        lblUsuario.setText(codUsuario);
    }
    
    public void cargarInterfaz(){
        coleccion = db.getCollection("partidos");
        DBCursor cursor = coleccion.find();
        while(cursor.hasNext()){
            DBObject actual = cursor.next();
            String numP = (String) actual.get("idPartido");
            if(numP.equals(SeleccionarPartido.numeroPartido)){
                String val1 = (String) actual.get("equipo1");
                String val2 = (String) actual.get("equipo2");
                lblInfo.setText("Partido:  " + val1 + "  VRS  " + val2);
                break;
            }
        }    
    }
    
    public void cargarDatos(){
        coleccion = db.getCollection("resumen");
        BasicDBObject document = new BasicDBObject();
	document.put("numeroPartido", SeleccionarPartido.numeroPartido);
        DBCursor cursor = coleccion.find(document);
        DefaultTableModel tb = (DefaultTableModel)tableRes.getModel();
        if(cursor.hasNext()){
            DBObject actual = cursor.next();
            String val1 = (String) actual.get("numeroPartido");
            String val2 = (String) actual.get("textoResumen");
            tb.addRow(new Object[] {val1, val2});
        }
        while(cursor.hasNext()){
           DBObject actual = cursor.next();
           String val1 = (String) actual.get("numeroPartido");
           String val2 = (String) actual.get("textoResumen");
           tb.addRow(new Object[] {val1, val2});
            //tableAficionado.setText(cursor.);
        }    
    }
    

    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableRes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnCComentario = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblInfo = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btnVerComentario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableRes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NumeroPartido", "Resumen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableRes);

        jLabel1.setText("Resumen");

        btnCComentario.setText("Crear Comentario");
        btnCComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCComentarioActionPerformed(evt);
            }
        });

        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        lblUsuario.setText("Usuario");

        btnVerComentario.setText("Ver Comentarios");
        btnVerComentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerComentarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(288, 288, 288))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnVerComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUsuario)
                .addGap(5, 5, 5)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCComentario)
                    .addComponent(btnVerComentario))
                .addGap(65, 65, 65)
                .addComponent(jButton3))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCComentarioActionPerformed
        CrearComentario ccom = new CrearComentario(this.numPartido,this.codUsuario);
        ccom.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCComentarioActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       SeleccionarPartido sPart = new SeleccionarPartido();
       sPart.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnVerComentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerComentarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerComentarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerComentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerComentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerComentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerComentarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerComentarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCComentario;
    private javax.swing.JButton btnVerComentario;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInfo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTable tableRes;
    // End of variables declaration//GEN-END:variables
}
